name: toolbox_builds
on: push
# on: workflow_dispatch
env:
  VERSION: '1.0.1'
  FEDORA_VER: '39'
  GO_VER: 'go1.21.4'
  RUST_VER: '1.74.0'
  RUSTUP_TAG: '1.26.0'
  RUSTARCH: 'x86_64-unknown-linux-gnu'
  REPO_OWNER: ${{ github.actor }}
  GITHUB_PASSWORD: ${{ github.token }}
  GITHUB_REGISTRY: ghcr.io/${{ github.repository_owner }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REPO_OWNER }}
          password: ${{ env.GITHUB_PASSWORD }}
          registry: ${{ env.GITHUB_REGISTRY }} 
      - name: build editor base
        run: |
          set -euxo pipefail
          FEDORA_VER=${{ env.FEDORA_VER }}
          CONTAINER=$(buildah from quay.io/toolbx-images/fedora-toolbox:${FEDORA_VER})
          buildah run ${CONTAINER} sh -c 'dnf -y install ninja-build cmake gcc make unzip gettext python3-pip age' &>/dev/null
          buildah run ${CONTAINER} sh -c 'dnf clean all'&>/dev/null
          echo 'NEOVIM'
          buildah run ${CONTAINER} sh -c 'git clone https://github.com/neovim/neovim && cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo && make install' &>/dev/null
          buildah run ${CONTAINER} sh -c 'which nvim && nvim --version'
          echo 'commit push neovim toolbox'
          buildah commit --rm ${CONTAINER} localhost/tbx_neovim:${FEDORA_VER}
          #buildah tag localhost/tbx_neovim:${FEDORA_VER} ghcr.io/${{ env.REPO_OWNER }}/tbx_neovim:${FEDORA_VER}
          #podman push ghcr.io/${{ env.REPO_OWNER }}/tbx_neovim:${FEDORA_VER}
