name: toolbox_builds
on: push
# on: workflow_dispatch
env:
  FEDORA_VER: '39'
  REPO_OWNER: ${{ github.actor }}
  GITHUB_PASSWORD: ${{ github.token }}
  GITHUB_REGISTRY: ghcr.io/${{ github.repository_owner }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # - name: Log in to quay.io
      #   uses: redhat-actions/podman-login@v1
      #   with:
      #     username: ${{ env.REGISTRY_USER }}
      #     password: ${{ env.GITHUB_PASSWORD }}
      #     registry: quay.io
      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REPO_OWNER }}
          password: ${{ env.GITHUB_PASSWORD }}
          registry: ${{ env.GITHUB_REGISTRY }} 
      - name: build base
        run: |
          set -euxo pipefail
          CONTAINER=$(buildah from quay.io/toolbx-images/fedora-toolbox:39)
          buildah run ${CONTAINER} sh -c 'dnf -y install ninja-build cmake gcc make unzip gettext' &>/dev/null
          buildah run ${CONTAINER} sh -c 'dnf clean all'&>/dev/null
          echo 'NEOVIM'
          buildah run ${CONTAINER} sh -c 'git clone https://github.com/neovim/neovim && cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo && make install' &>/dev/null
          buildah run ${CONTAINER} sh -c 'which nvim && nvim --version'
          echo 'commit push neovim toolbox'
          buildah commit --rm ${CONTAINER} ghcr.io/${{ env.REPO_OWNER }}/tbx_neovim:${FEDORA_VER}
          podman push ghcr.io/${{ env.REPO_OWNER }}/tbx_neovim:${FEDORA_VER}
      - name: build wasmtime and spin cli 
        run: |
          set -euxo pipefail
          CONTAINER=$(buildah from ghcr.io/${{ env.REPO_OWNER }}/tbx_neovim:${FEDORA_VER})
          echo 'WASMTIME'
          buildah config --env WASMTIME_HOME=/usr/local/wasmtime ${CONTAINER}
          buildah run ${CONTAINER} sh -c "touch ~/.profile && curl https://wasmtime.dev/install.sh -sSf | bash"
          buildah run ${CONTAINER} sh -c 'ln -sf /usr/local/wasmtime/bin/* /usr/local/bin/'
          buildah run ${CONTAINER} sh -c 'which wasmtime && wasmtime --help'
          buildah commit --rm ${CONTAINER} ghcr.io/${{ env.REPO_OWNER }}/tbx_wasmtime:${FEDORA_VER}
          echo 'SPIN'
          buildah run ${CONTAINER} sh -c 'mkdir -p /usr/local/spin '
          buildah run ${CONTAINER} sh -c 'cd /usr/local/spin && curl -fsSL https://developer.fermyon.com/downloads/install.sh | bash' &>/dev/null
          buildah run ${CONTAINER} sh -c 'cd /usr/local/spin && ls -al .'
          buildah run ${CONTAINER} sh -c 'ln -s /usr/local/spin/spin /usr/local/bin/'
          buildah run {CONTAINER} sh -c 'which spin && spin --version && spin --help'
          podman images
