name: toolbox_builds
on: push
# on: workflow_dispatch
env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: base fedora container image
        run: make fedora
      - name: golang
        run: make golang
      - name: wasmtime
        run: make wasmtime
      - name: spin
        run: make spin
      - name: rustup
        run: make rustup
      - name: toolbox container image
        run: make tbx
      #   run: make tbx
      #      - uses: redhat-actions/podman-login@v1
        # with:
        #   username: ${{ env.REGISTRY_USER }}
        #   password: ${{ env.REGISTRY_PASSWORD }}
        #   registry: ${{ env.IMAGE_REGISTRY }}
