name: toolbox_builds
on: push
# on: workflow_dispatch
  # permissions:
  #    contents: read
  #    packages: write
#
# env:
#   REGISTRY_USER: ${{ github.actor }}
#   REGISTRY_PASSWORD: ${{ github.token }}
#   IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
jobs:
  build_base:
    uses: ./.github/workflows/build_base.yml
  rustup:
    needs: build_base
    uses: ./.github/workflows/rustup.yml
  wasmtime:
    needs: build_base
    uses: ./.github/workflows/wasmtime.yml
    #
    # steps:
    #   - uses: actions/checkout@v4
    #   - uses: redhat-actions/podman-login@v1
    #     with:
    #       username: ${{ env.REGISTRY_USER }}
    #       password: ${{ env.REGISTRY_PASSWORD }}
    #       registry: ${{ env.IMAGE_REGISTRY }}
    #   - name: build base image
    #     run: make version && make build-base
    #   - name: build rustup
    #     run: make rustup
      # - name: spin
      #   run: make spin
      # - name: wasm
      #   run: make wasmtime
      # - name: build golang
      #   run: make golang
      # - name: build neovim
      #   run: make neovim
      # - name: build and push tbx image
      #   run: make tbx
      #
 # permissions:
    #   contents: read
    #   packages: write
