name: CI
on: push
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container: quay.io/toolbx-images/fedora-toolbox:39
    steps:
      - name: build
        run: |
          dnf -y install ninja-build cmake gcc make unzip gettext
