name: toolbox_builds
on: push
# on: workflow_dispatch
env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: build fedora base image
        run: make fedora
      # - name: spinning top
      #   run: make spin
      # - name: wasmtime
      #   run: make wasmtime
      - name: neovim
        run: make neovim
      - name: golang
            run: make golang

      # - name: add rust tooling
      #   run: make rustup
          # - name: build base image
      #   run: make version && make build-base
      # - name: build and push tbx image
      #   run: make tbx
      #      - uses: redhat-actions/podman-login@v1
        # with:
        #   username: ${{ env.REGISTRY_USER }}
        #   password: ${{ env.REGISTRY_PASSWORD }}
        #   registry: ${{ env.IMAGE_REGISTRY }}
