name: toolbox_builds
on: push
# on: workflow_dispatch
env:
    IMAGE_NAME: boxkit
    IMAGE_TAGS: latest
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: redhat-actions/podman-login
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build base image
        run: make version && make base
      - name: build and push tbx image
        run: make tbx
      - name: inspect
        run: podman images
