name: toolbox_builds
on: push
# on: workflow_dispatch
env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: base container image
        run: make fedora
      - name: wasmtime
        run: make wasmtime
      - name: spin
        run: make spin
      - name: toolbox container image
        run: make tbx
      # - name: rust tooling
      #   run: make rustup && make rust-tooling
      # - name: spinning top
      #   run: make spin
      # - name: maker
      #   run: |
      #     make neovim
          # make wasmtime
          # make golang
          # make rustup
          # make spin
      # - name: pusher
      #   run: make tbx
      #      - uses: redhat-actions/podman-login@v1
        # with:
        #   username: ${{ env.REGISTRY_USER }}
        #   password: ${{ env.REGISTRY_PASSWORD }}
        #   registry: ${{ env.IMAGE_REGISTRY }}
