name: rustup
on: workflow_call
# on: workflow_dispatch
jobs:
  rustup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: build-base
      - name: Load Image
        run: |
          podman load --input build-base.tar
          VERSION=$(podman images --noheading --format "{{.Tag}}")
	        sed -i "s/ALPINE_VER=.*/ALPINE_VER=${VERSION}/" .env
	        make rustup
         #  CONTAINER=$(buildah from localhost/build-base:$ALPINE_VER)
	        # buildah config \
		       #  --env RUSTUP_HOME=/usr/local/rustup \
		       #  --env CARGO_HOME=/usr/local/cargo \
		       #  ${CONTAINER} 
	        # # buildah run $${CONTAINER} sh -c "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
	        # # https://github.com/rust-lang/rustup/tags
	        # buildah run ${CONTAINER} sh -c "wget https://static.rust-lang.org/rustup/archive/$RUSTUP_TAG/$RUSTARCH/rustup-init "
	        # buildah run ${CONTAINER} sh -c "chmod +x rustup-init" || true
	        # buildah run ${CONTAINER} sh -c './rustup-init -y --no-modify-path --profile minimal --default-toolchain $RUST_VER --default-host $RUSTARCH'
	        # buildah run ${CONTAINER} sh -c 'chmod -R a+w /usr/local/rustup /usr/local/cargo && ln -s /usr/local/cargo/bin/* /usr/local/bin/'
	        # buildah run ${CONTAINER} sh -c 'echo " --[[ CHECKS ]]--"'
	        # buildah run ${CONTAINER} sh -c 'rustup --version && cargo --version && rustc --version'
	        # buildah commit --rm ${CONTAINER} localhost/build-base:$ALPINE_VER
